ALTER SESSION SET CONTAINER="poolname";
--CREATE USER HERA IDENTIFIED BY "HERASTG";
GRANT CREATE SESSION, CONNECT, RESOURCE TO HERAAPP; 
GRANT SELECT ON SYS.V_$SESSION TO HERAAPP;

conn heraapp/heraappstg@localhost/poolname

CREATE TABLE POOL_DETAILS (ID INT, NAME VARCHAR(30));
INSERT INTO POOL_DETAILS (ID, NAME) VALUES (1, 'occ-ruser');

--grant select on pool_details to heraapp;

COMMIT;
