ALTER SESSION SET CONTAINER="poolname";
--CREATE USER HERA IDENTIFIED BY "HERASTG";
GRANT CREATE SESSION, CONNECT, RESOURCE TO HERAAPP; 
GRANT SELECT ON SYS.V_$SESSION TO HERAAPP;
GRANT SELECT ON SYS.V_$SQL TO HERAAPP;
GRANT SELECT ON SYS.V_$SESSTAT TO HERAAPP;
GRANT SELECT ON SYS.V_$STATNAME TO HERAAPP;

conn heraapp/heraappstg@localhost/poolname

CREATE TABLE POOL_DETAILS (ID INT, NAME VARCHAR(30));
INSERT INTO POOL_DETAILS (ID, NAME) VALUES (1, 'occ-ruser');

CREATE TABLE user (user_id NUMBER PRIMARY KEY, name VARCHAR2(50) NOT NULL, email VARCHAR2(100), created_date DATE DEFAULT SYSDATE);

--grant select on pool_details to heraapp;

COMMIT;
